// Generated by gencpp from file skeleton/JointMsg.msg
// DO NOT EDIT!


#ifndef SKELETON_MESSAGE_JOINTMSG_H
#define SKELETON_MESSAGE_JOINTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace skeleton
{
template <class ContainerAllocator>
struct JointMsg_
{
  typedef JointMsg_<ContainerAllocator> Type;

  JointMsg_()
    : joints()  {
    }
  JointMsg_(const ContainerAllocator& _alloc)
    : joints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::skeleton::JointMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skeleton::JointMsg_<ContainerAllocator> const> ConstPtr;

}; // struct JointMsg_

typedef ::skeleton::JointMsg_<std::allocator<void> > JointMsg;

typedef boost::shared_ptr< ::skeleton::JointMsg > JointMsgPtr;
typedef boost::shared_ptr< ::skeleton::JointMsg const> JointMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skeleton::JointMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skeleton::JointMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace skeleton

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'skeleton': ['/home/brucechen/dosubot_ws/src/skeleton/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::skeleton::JointMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skeleton::JointMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton::JointMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton::JointMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton::JointMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton::JointMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skeleton::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1202c50759ccad57166aaeb5af77c4fa";
  }

  static const char* value(const ::skeleton::JointMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1202c50759ccad57ULL;
  static const uint64_t static_value2 = 0x166aaeb5af77c4faULL;
};

template<class ContainerAllocator>
struct DataType< ::skeleton::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skeleton/JointMsg";
  }

  static const char* value(const ::skeleton::JointMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skeleton::JointMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] joints \n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::skeleton::JointMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skeleton::JointMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skeleton::JointMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skeleton::JointMsg_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKELETON_MESSAGE_JOINTMSG_H
