(cl:defpackage xm_arm_msgs-msg
  (:use )
  (:export
   "<XM_ARMGRIPPERCOMMAND>"
   "XM_ARMGRIPPERCOMMAND"
   "<XM_ARMGRIPPERCOMMANDACTION>"
   "XM_ARMGRIPPERCOMMANDACTION"
   "<XM_ARMGRIPPERCOMMANDACTIONFEEDBACK>"
   "XM_ARMGRIPPERCOMMANDACTIONFEEDBACK"
   "<XM_ARMGRIPPERCOMMANDACTIONGOAL>"
   "XM_ARMGRIPPERCOMMANDACTIONGOAL"
   "<XM_ARMGRIPPERCOMMANDACTIONRESULT>"
   "XM_ARMGRIPPERCOMMANDACTIONRESULT"
   "<XM_ARMGRIPPERCOMMANDFEEDBACK>"
   "XM_ARMGRIPPERCOMMANDFEEDBACK"
   "<XM_ARMGRIPPERCOMMANDGOAL>"
   "XM_ARMGRIPPERCOMMANDGOAL"
   "<XM_ARMGRIPPERCOMMANDRESULT>"
   "XM_ARMGRIPPERCOMMANDRESULT"
   "<XM_ARMSERIALDATA>"
   "XM_ARMSERIALDATA"
   "<XM_ARMSERIALDATAGRAM>"
   "XM_ARMSERIALDATAGRAM"
  ))

