; Auto-generated. Do not edit!


(cl:in-package xm_arm_msgs-msg)


;//! \htmlinclude xm_ArmGripperCommandResult.msg.html

(cl:defclass <xm_ArmGripperCommandResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass xm_ArmGripperCommandResult (<xm_ArmGripperCommandResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <xm_ArmGripperCommandResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'xm_ArmGripperCommandResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name xm_arm_msgs-msg:<xm_ArmGripperCommandResult> is deprecated: use xm_arm_msgs-msg:xm_ArmGripperCommandResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <xm_ArmGripperCommandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader xm_arm_msgs-msg:finish-val is deprecated.  Use xm_arm_msgs-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <xm_ArmGripperCommandResult>) ostream)
  "Serializes a message object of type '<xm_ArmGripperCommandResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <xm_ArmGripperCommandResult>) istream)
  "Deserializes a message object of type '<xm_ArmGripperCommandResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<xm_ArmGripperCommandResult>)))
  "Returns string type for a message object of type '<xm_ArmGripperCommandResult>"
  "xm_arm_msgs/xm_ArmGripperCommandResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'xm_ArmGripperCommandResult)))
  "Returns string type for a message object of type 'xm_ArmGripperCommandResult"
  "xm_arm_msgs/xm_ArmGripperCommandResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<xm_ArmGripperCommandResult>)))
  "Returns md5sum for a message object of type '<xm_ArmGripperCommandResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'xm_ArmGripperCommandResult)))
  "Returns md5sum for a message object of type 'xm_ArmGripperCommandResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<xm_ArmGripperCommandResult>)))
  "Returns full string definition for message of type '<xm_ArmGripperCommandResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'xm_ArmGripperCommandResult)))
  "Returns full string definition for message of type 'xm_ArmGripperCommandResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <xm_ArmGripperCommandResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <xm_ArmGripperCommandResult>))
  "Converts a ROS message object to a list"
  (cl:list 'xm_ArmGripperCommandResult
    (cl:cons ':finish (finish msg))
))
