; Auto-generated. Do not edit!


(cl:in-package xm_arm_msgs-msg)


;//! \htmlinclude xm_ArmGripperCommandGoal.msg.html

(cl:defclass <xm_ArmGripperCommandGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type xm_arm_msgs-msg:xm_ArmGripperCommand
    :initform (cl:make-instance 'xm_arm_msgs-msg:xm_ArmGripperCommand)))
)

(cl:defclass xm_ArmGripperCommandGoal (<xm_ArmGripperCommandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <xm_ArmGripperCommandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'xm_ArmGripperCommandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name xm_arm_msgs-msg:<xm_ArmGripperCommandGoal> is deprecated: use xm_arm_msgs-msg:xm_ArmGripperCommandGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <xm_ArmGripperCommandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader xm_arm_msgs-msg:command-val is deprecated.  Use xm_arm_msgs-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <xm_ArmGripperCommandGoal>) ostream)
  "Serializes a message object of type '<xm_ArmGripperCommandGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'command) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <xm_ArmGripperCommandGoal>) istream)
  "Deserializes a message object of type '<xm_ArmGripperCommandGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'command) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<xm_ArmGripperCommandGoal>)))
  "Returns string type for a message object of type '<xm_ArmGripperCommandGoal>"
  "xm_arm_msgs/xm_ArmGripperCommandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'xm_ArmGripperCommandGoal)))
  "Returns string type for a message object of type 'xm_ArmGripperCommandGoal"
  "xm_arm_msgs/xm_ArmGripperCommandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<xm_ArmGripperCommandGoal>)))
  "Returns md5sum for a message object of type '<xm_ArmGripperCommandGoal>"
  "bbdf141ff7e4fd37d8aa342f2709b46e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'xm_ArmGripperCommandGoal)))
  "Returns md5sum for a message object of type 'xm_ArmGripperCommandGoal"
  "bbdf141ff7e4fd37d8aa342f2709b46e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<xm_ArmGripperCommandGoal>)))
  "Returns full string definition for message of type '<xm_ArmGripperCommandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%xm_arm_msgs/xm_ArmGripperCommand command~%~%================================================================================~%MSG: xm_arm_msgs/xm_ArmGripperCommand~%float64 position~%float64 torque~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'xm_ArmGripperCommandGoal)))
  "Returns full string definition for message of type 'xm_ArmGripperCommandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%xm_arm_msgs/xm_ArmGripperCommand command~%~%================================================================================~%MSG: xm_arm_msgs/xm_ArmGripperCommand~%float64 position~%float64 torque~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <xm_ArmGripperCommandGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <xm_ArmGripperCommandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'xm_ArmGripperCommandGoal
    (cl:cons ':command (command msg))
))
