// Auto-generated. Do not edit!

// (in-package xm_arm_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let xm_ArmGripperCommand = require('./xm_ArmGripperCommand.js');

//-----------------------------------------------------------

class xm_ArmGripperCommandGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.command = null;
    }
    else {
      if (initObj.hasOwnProperty('command')) {
        this.command = initObj.command
      }
      else {
        this.command = new xm_ArmGripperCommand();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type xm_ArmGripperCommandGoal
    // Serialize message field [command]
    bufferOffset = xm_ArmGripperCommand.serialize(obj.command, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type xm_ArmGripperCommandGoal
    let len;
    let data = new xm_ArmGripperCommandGoal(null);
    // Deserialize message field [command]
    data.command = xm_ArmGripperCommand.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'xm_arm_msgs/xm_ArmGripperCommandGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bbdf141ff7e4fd37d8aa342f2709b46e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Goal
    xm_arm_msgs/xm_ArmGripperCommand command
    
    ================================================================================
    MSG: xm_arm_msgs/xm_ArmGripperCommand
    float64 position
    float64 torque
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new xm_ArmGripperCommandGoal(null);
    if (msg.command !== undefined) {
      resolved.command = xm_ArmGripperCommand.Resolve(msg.command)
    }
    else {
      resolved.command = new xm_ArmGripperCommand()
    }

    return resolved;
    }
};

module.exports = xm_ArmGripperCommandGoal;
