xm_arm:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - joint_lift
    - joint_waist
    - joint_big_arm
    - joint_forearm
    - joint_wrist_pitching
    - joint_wrist_rotation
    gains:
      joint_lift:           {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_waist:          {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_big_arm:        {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_forearm:        {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_wrist_pitching: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_wrist_rotation: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_finger_left
      - joint_finger_right
    gains:
      joint_finger_left:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      joint_finger_right: {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
