// Generated by gencpp from file xm_arm_msgs/xm_ArmGripperCommandActionGoal.msg
// DO NOT EDIT!


#ifndef XM_ARM_MSGS_MESSAGE_XM_ARMGRIPPERCOMMANDACTIONGOAL_H
#define XM_ARM_MSGS_MESSAGE_XM_ARMGRIPPERCOMMANDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <xm_arm_msgs/xm_ArmGripperCommandGoal.h>

namespace xm_arm_msgs
{
template <class ContainerAllocator>
struct xm_ArmGripperCommandActionGoal_
{
  typedef xm_ArmGripperCommandActionGoal_<ContainerAllocator> Type;

  xm_ArmGripperCommandActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  xm_ArmGripperCommandActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::xm_arm_msgs::xm_ArmGripperCommandGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct xm_ArmGripperCommandActionGoal_

typedef ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<std::allocator<void> > xm_ArmGripperCommandActionGoal;

typedef boost::shared_ptr< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal > xm_ArmGripperCommandActionGoalPtr;
typedef boost::shared_ptr< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal const> xm_ArmGripperCommandActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xm_arm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'xm_arm_msgs': ['/home/brucechen/dosubot_ws/src/xm_arm_msgs/msg', '/home/brucechen/dosubot_ws/devel/share/xm_arm_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "672b2b001474d12e45605d8783619f88";
  }

  static const char* value(const ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x672b2b001474d12eULL;
  static const uint64_t static_value2 = 0x45605d8783619f88ULL;
};

template<class ContainerAllocator>
struct DataType< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xm_arm_msgs/xm_ArmGripperCommandActionGoal";
  }

  static const char* value(const ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
xm_ArmGripperCommandGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: xm_arm_msgs/xm_ArmGripperCommandGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Goal\n\
xm_arm_msgs/xm_ArmGripperCommand command\n\
\n\
================================================================================\n\
MSG: xm_arm_msgs/xm_ArmGripperCommand\n\
float64 position\n\
float64 torque\n\
";
  }

  static const char* value(const ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xm_ArmGripperCommandActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xm_arm_msgs::xm_ArmGripperCommandActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::xm_arm_msgs::xm_ArmGripperCommandGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XM_ARM_MSGS_MESSAGE_XM_ARMGRIPPERCOMMANDACTIONGOAL_H
